version: 1.0.{build}
image: Visual Studio 2022

configuration: Release

init:
- ps: Update-AppveyorBuild -Version "$env:appveyor_build_version+build.{build}+sha.$($env:appveyor_repo_commit.substring(0,8))"

nuget:
  disable_publish_on_pr: true
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '1.0.{build}.0'
  file_version: '1.0.{build}.0'
  informational_version: '{version}'

matrix:
  fast_finish: true # fail fast!

clone_depth: 3  

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd: dotnet restore src/DotJEM.StructureQL.sln # Restores .NET Standard

build:
  project: src/DotJEM.StructureQL.sln
  publish_nuget: true
  publish_nuget_symbols: true

test:
  assemblies:
    - '**\*.Test.dll'

deploy:
  provider: NuGet
  api_key:
    secure: 54AfgNojEqST++WD6E8lCMjHx6yl4JUPt/Wruh6eWRiLsPtfTew6mnVVzYFlDWwo
  skip_symbols: false
  on:
    branch: main
